---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list 
# of plays, with each play being a dictionary
-
 
  # Target: where our play will run and options it will run with
  hosts: web
  user: root
  gather_facts: false

  # Variable: variables that will apply to the play, on all target systems
  vars:
    motd: "Welcome to Lock 4 Ansible Never Rock never\n"
  # Task: the list of tasks that will be executed within the playbook
  tasks:
    - name: Configure a MOTD (message of the day)
      copy:
        content: "{{ motd }}"
        dest: /etc/motd
      notify: MOTD changed
   - name: Copying my Readme file to tmp folder
     copy:
       src: readme
       dest: /tmp
     notify: COPY Temp

  # Handlers: handlers that are executed as a notify key from a task
  handlers:
    - name: MOTD changed
      debug:
        msg: The Motd has changed
    - name: COPY Temp
      debug:
        msg: Added readme file to the tmp directory
  # Roles: list of roles to be imported into the play

# Three dots indicate the end of a YAML document
...
